# Olzhas Akylbekov

### Lab2 - KNN with iris dataset

Loading libraries: 

In [383]:
import numpy as np
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_iris
from sklearn import datasets
from sklearn.model_selection import train_test_split
import pandas as pd
from sklearn import metrics

Loading datasets:

In [384]:
training_set = []
test_set = []
target=load_iris().target.reshape(150,1)
dataset=np.c_[data,target]

Splitting data frame into the test and train sets:

In [385]:
training_set, test_set = train_test_split(dataset, random_state = 0)
print('The shape of the Train set:',training_set.shape)
print('The shape of the Test set:',test_set.shape)

The shape of the Train set: (112, 5)
The shape of the Test set: (38, 5)


Creating the function which calculates 
#### EUCLIDEAN DISTANCE:

In [386]:
def euclidean_distance(point1, point2,l):
    distance = 0.0
    for i in range(l):
        distance +=pow((point1[i] - point2[i]), 2)
    return np.sqrt(distance)

Creating function to Generate the list of nearest neighbors k

In [387]:
def get_neighbors(training_set, test_instance, k):
    distances = []
    l = len(test_instance) - 1
    t=len(training_set)
    for i in range(t):
        distance = euclidean_distance(test_instance, training_set[i], l)
        distances.append((training_set[i], distance))
    distances.sort(key=lambda i: i[1])
    neighbors = []
    for i in range(k):
        neighbors.append(distances[i][0])
    return neighbors


Creating function to  

In [388]:
def get_response(neighbors):
    class_votes = {}
    r =len(neighbors)
    for i in range(r):
        response = neighbors[i][-1]
        if response in class_votes:
            class_votes[response] += 1
        else:
            class_votes[response] = 1
    sorted_votes = sorted(class_votes.items(), key=operator.itemgetter(1), reverse=True)
    return sorted_votes[0][0]

By using above defined functions we gets predictions for our test sets

In [389]:
predictions = []
k = 5
r =len(test_set)
for i in range(r):
    neighbors = get_neighbors(training_set, test_set[i], k)
    result = get_response(neighbors)
    predictions.append(result)


Getting original result form datasets

In [390]:
test_set_real=[]
for i in range(r):
    test_set_real.append(test_set[[i],4])

In [391]:
accuracy = accuracy_score(test_set_real, predictions)
print('The Accuracy of KNN: ', round(accuracy,2), '%')

The Accuracy of KNN:  0.97 %


## Lab2 - SVM with iris dataset

In [392]:
#Import scikit-learn dataset library
from sklearn import svm
clf = svm.SVC(kernel='linear') 

#Load dataset
iris = datasets.load_iris()

In [393]:
print("Features: ", iris.feature_names)
print("Labels: ", iris.target_names)

Features:  ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Labels:  ['setosa' 'versicolor' 'virginica']


In [394]:
iris.data.shape

(150, 4)

In [395]:
print(iris.data[0:5]) 

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [396]:
print(iris.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


#### Splitiing data sets into 70% training and 30% test

In [397]:
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.3,random_state=109) 

Fitting moldes with train data sets

In [398]:
clf.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

Getting result of prediction

In [399]:
y_pred = clf.predict(X_test)

Showing accuracy of trained model

In [400]:
print("The Accuracy of SVM:",round(metrics.accuracy_score(y_test, y_pred),2),'%')

The Accuracy of SVM: 0.96 %
